--- 

- name: Apt Update
  apt:
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Install Essentials
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - golang-go
    - net-tools
    - network-manager
    - tmux
    - rclone
    - neofetch
    - zsh

- name: Install Oh My Zsh for specific users
  become: true
  become_user: "{{ item }}"
  shell: |
    if [ ! -d "$HOME/.oh-my-zsh" ]; then
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    fi
  with_items: "{{ ohmyzsh_users }}"
  args:
    executable: /bin/bash

- name: Set zsh as default shell for specific users
  become: true
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items: "{{ ohmyzsh_users }}"